### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by qwwqwwq** [bayeshack2016/vetafi#2]
What is the purpose of this line: https://github.com/bayeshack2016/vetafi/blob/master/winterfell/app.js#L13

Getting the following exception when I try to run the server:

`Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jeffreyquinn/Code/VA_hackathon/vetaffi/winterfell/middlewares/passport.js:1:71)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)`

**Comment by ahsu1230** [comment]
That function goes through every file in a folder (for example, middlewares), includes them and imports them into the app as modules.
That way, we don't have to do:
require(/../middlewares/A)
require(/../middlewares/B)
require(/../middlewares/C)
require(/../controllers/A)
...
