### ISSUE TITLE
Aaron's biscuit is bad

### ISSUE THREAD

**Issue by ahsu1230** [bayeshack2016/vetafi#76]
I have to comment out biscuit related things in order to run our server, even on vagrant.

I get the following errors:

```
1|Express  | environment: "local"
1|Express  | Listening on port 3999. Winter is coming!
1|Express  | Redis connected at localhost:6379
1|Express  | Database connection opened at 0.0.0.0:27017
1|Express  | Error: Command failed: biscuit get -f /vagrant/config/biscuit/secrets.yaml 'local::lob-api-key'
1|Express  | Warning: decryption under kms failed: NoCredentialProviders: no valid providers in chain. Deprecated. 
1|Express  |    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
1|Express  | Warning: decryption under kms failed: NoCredentialProviders: no valid providers in chain. Deprecated. 
1|Express  |    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
1|Express  | Warning: decryption under kms failed: NoCredentialProviders: no valid providers in chain. Deprecated. 
1|Express  |    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
1|Express  | NoCredentialProviders: no valid providers in chain. Deprecated. 
1|Express  |    For verbose messaging see aws.Config.CredentialsChainVerboseErrors
1|Express  |     at ChildProcess.exithandler (child_process.js:202:12)
1|Express  |     at emitTwo (events.js:100:13)
1|Express  |     at ChildProcess.emit (events.js:185:7)
1|Express  |     at maybeClose (internal/child_process.js:850:16)
1|Express  |     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by qwwqwwq** [comment]
Im pretty sure that error message just means your .aws/config file is not
set up

**Comment by ahsu1230** [comment]
oh hm. It's that file is not there for me anymore.
What do I need in it again?

**Comment by qwwqwwq** [comment]
It should have your aws key and secret key, if you google aws credentials
file should be able to find an example easily
